#!/usr/bin/env python3
"""
ray_launch_megatron.py -- Launch `megatron sft` on all GPU nodes via Ray (no inter-node SSH required)

Why this script is needed:
  Megatron-SWIFT does not have built-in Ray integration like `swift sft --use_ray=true` (it uses torchrun).
  But torchrun is a single-node launcher; multi-node requires either SSH (traditional) or an external scheduler.
  This script uses Ray as a "passwordless SSH" alternative: you run `ray start` on each machine to form a cluster,
  then this script dispatches `megatron sft` as a Ray task to each node -- no inter-node SSH needed.

Workflow:
  1. On each node, run `bash start_ray.sh head/worker` to bring up the Ray cluster (start_ray.sh
     auto-detects the NCCL network interface and saves it to .nccl_env)
  2. On the head node, run `bash train_megatron_ray.sh` (which calls this script)
  3. This script:
     - ray.init() connects to the cluster
     - Lists all GPU nodes; node[0] becomes master
     - Launches one Ray task per node with num_gpus=8, pinned via NodeAffinity
     - Each task runs `megatron sft <args>` in a subprocess with NODE_RANK/MASTER_ADDR/NCCL env set
     - Waits for all tasks to finish

Usage:
  python ray_launch_megatron.py [--gpus-per-node 8] [--master-port 29500] [--nccl-env .nccl_env] -- <megatron_args...>

  Note: everything after `--` is passed through verbatim as megatron sft arguments.
"""

from __future__ import annotations

import argparse
import os
import shlex
import sys
from pathlib import Path
from typing import Dict, List


def parse_nccl_env_file(path: Path) -> Dict[str, str]:
    """Parse a .nccl_env file (`export KEY=VAL` lines) into a dict."""
    out: Dict[str, str] = {}
    if not path.exists():
        return out
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export "):]
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            out[k] = v
    return out


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--gpus-per-node", type=int, default=8)
    p.add_argument(
        "--master-port",
        type=int,
        default=int(os.environ.get("MASTER_PORT", "29500")),
        help="Preferred torchrun master port. If busy on rank0 node, the launcher picks the next free port.",
    )
    p.add_argument(
        "--nccl-env",
        default=str(Path(__file__).parent / ".nccl_env"),
        help="Path to .nccl_env file (generated by start_ray.sh).",
    )
    p.add_argument(
        "--ray-address",
        default="auto",
        help="Ray cluster address. Default 'auto' = autodetect running Ray.",
    )
    p.add_argument(
        "--no-cleanup",
        action="store_true",
        help="Do not kill stale Megatron/torchrun processes on Ray nodes before launching.",
    )
    p.add_argument(
        "--cleanup-only",
        action="store_true",
        help="Kill stale Megatron processes on Ray nodes and exit without launching training.",
    )
    p.add_argument(
        "--skip-path-check",
        action="store_true",
        help="Skip checking --model and --cached_dataset paths on all Ray nodes before launching.",
    )
    # Everything after `--` is passed verbatim to `megatron sft`.
    args, rest = p.parse_known_args()
    if rest and rest[0] == "--":
        rest = rest[1:]
    if not rest and not args.cleanup_only:
        print("ERROR: no megatron sft args given. Pass them after '--'", file=sys.stderr)
        print("Example: python ray_launch_megatron.py -- --model Qwen/... --cached_dataset ... ...", file=sys.stderr)
        return 2

    megatron_args: List[str] = list(rest)

    # Lazy import so --help works without ray installed.
    try:
        import ray
        from ray.util.scheduling_strategies import NodeAffinitySchedulingStrategy
    except ImportError:
        print("ERROR: ray is not installed. Run `pip install 'ray[default]'`.", file=sys.stderr)
        return 2

    nccl_env = parse_nccl_env_file(Path(args.nccl_env))

    print(f"[ray-launch] connecting to ray cluster at {args.ray_address!r}...")
    ray.init(address=args.ray_address, log_to_driver=True)

    # Collect alive GPU nodes
    nodes = [
        n for n in ray.nodes()
        if n.get("Alive") and int(n.get("Resources", {}).get("GPU", 0)) >= args.gpus_per_node
    ]
    nodes.sort(key=lambda n: n["NodeID"])  # deterministic
    if not nodes:
        print("ERROR: no Ray nodes with enough GPUs found", file=sys.stderr)
        return 2

    nnodes = len(nodes)
    master_node = nodes[0]
    master_addr = master_node["NodeManagerAddress"]

    @ray.remote(num_cpus=0)
    def cleanup_stale_processes() -> tuple[str, str]:
        import os
        import signal
        import socket
        import subprocess
        import time

        this_pid = os.getpid()
        parent_pid = os.getppid()
        ps = subprocess.run(
            ["ps", "-eo", "pid=,ppid=,args="],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
        patterns = (
            "megatron sft",
            "swift/cli/_megatron/sft.py",
        )
        victims: list[int] = []
        lines: list[str] = []
        for raw_line in ps.stdout.splitlines():
            line = raw_line.strip()
            parts = line.split(None, 2)
            if len(parts) < 3:
                continue
            pid = int(parts[0])
            ppid = int(parts[1])
            cmd = parts[2]
            if pid in (this_pid, parent_pid) or ppid == this_pid:
                continue
            if any(pattern in cmd for pattern in patterns):
                victims.append(pid)
                lines.append(line)

        if not victims:
            return socket.gethostname(), "no stale megatron/torchrun processes"

        for pid in victims:
            try:
                os.kill(pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
        time.sleep(3)
        for pid in victims:
            try:
                os.kill(pid, 0)
            except ProcessLookupError:
                continue
            try:
                os.kill(pid, signal.SIGKILL)
            except ProcessLookupError:
                pass

        return socket.gethostname(), "killed:\n" + "\n".join(lines)

    if not args.no_cleanup:
        print("[ray-launch] cleaning stale Megatron/torchrun processes on all Ray nodes...")
        cleanup_refs = [
            cleanup_stale_processes.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=node["NodeID"], soft=False),
            ).remote()
            for node in nodes
        ]
        for host, msg in ray.get(cleanup_refs):
            print(f"[ray-launch] cleanup {host}: {msg}")
        print()
        if args.cleanup_only:
            print("[ray-launch] cleanup-only done")
            return 0

    def values_after(flag: str) -> List[str]:
        values: List[str] = []
        for i, item in enumerate(megatron_args[:-1]):
            if item == flag:
                values.append(megatron_args[i + 1])
        return values

    paths_to_check = values_after("--model") + values_after("--cached_dataset") + values_after("--cached_val_dataset")

    @ray.remote(num_cpus=0)
    def check_paths(paths: List[str]) -> tuple[str, List[tuple[str, bool, str]]]:
        import os
        import socket

        results: List[tuple[str, bool, str]] = []
        for path in paths:
            exists = os.path.exists(path)
            if exists:
                if os.path.isdir(path):
                    try:
                        entries = os.listdir(path)
                        detail = f"dir, {len(entries)} entries"
                    except OSError as exc:
                        detail = f"dir, list failed: {exc}"
                else:
                    try:
                        detail = f"file, {os.path.getsize(path)} bytes"
                    except OSError as exc:
                        detail = f"file, stat failed: {exc}"
            else:
                detail = "missing"
            results.append((path, exists, detail))
        return socket.gethostname(), results

    if paths_to_check and not args.skip_path_check:
        print("[ray-launch] checking model/data paths on all Ray nodes...")
        check_refs = [
            check_paths.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=node["NodeID"], soft=False),
            ).remote(paths_to_check)
            for node in nodes
        ]
        missing: List[tuple[str, str]] = []
        for host, results in ray.get(check_refs):
            for path, exists, detail in results:
                status = "OK" if exists else "MISSING"
                print(f"[ray-launch] path-check {host}: {status} {path} ({detail})")
                if not exists:
                    missing.append((host, path))
        if missing:
            print("", file=sys.stderr)
            print("[ray-launch] FAILED: required path(s) missing on Ray node(s):", file=sys.stderr)
            for host, path in missing:
                print(f"  {host}: {path}", file=sys.stderr)
            print("", file=sys.stderr)
            print("Fix DATA_PATH/MODEL_PATH or make the same local path visible on every node before training.", file=sys.stderr)
            return 2
        print()

    @ray.remote(num_cpus=0)
    def choose_master_port(preferred_port: int) -> tuple[int, str]:
        import socket

        def can_bind(port: int) -> bool:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                try:
                    sock.bind(("", port))
                    return True
                except OSError:
                    return False

        if preferred_port > 0:
            if can_bind(preferred_port):
                return preferred_port, f"preferred port {preferred_port} is free"
            for port in range(preferred_port + 1, preferred_port + 201):
                if can_bind(port):
                    return port, f"preferred port {preferred_port} is busy; using {port}"

        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("", 0))
            port = sock.getsockname()[1]
        return port, f"selected ephemeral free port {port}"

    master_port, port_msg = ray.get(
        choose_master_port.options(
            scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=master_node["NodeID"], soft=False),
        ).remote(args.master_port)
    )

    print(f"[ray-launch] cluster: {nnodes} nodes, {args.gpus_per_node} GPUs each, master={master_addr}:{master_port}")
    for i, n in enumerate(nodes):
        print(f"  node{i}: {n['NodeManagerAddress']:>15}  {int(n['Resources']['GPU'])} GPUs  {n['NodeID'][:12]}...")

    print(f"[ray-launch] master port: {port_msg}")
    print(f"[ray-launch] NCCL env loaded from {args.nccl_env}: {list(nccl_env.keys()) or '(empty)'}")
    print(f"[ray-launch] megatron args: {' '.join(shlex.quote(a) for a in megatron_args)}")
    print()

    # Build base env to inject into every node's Ray task
    base_env = {
        "USE_HF": "1",
        "CUDA_DEVICE_MAX_CONNECTIONS": "1",
        "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
        "MASTER_ADDR": str(master_addr),
        "MASTER_PORT": str(master_port),
        "NNODES": str(nnodes),
        "NPROC_PER_NODE": str(args.gpus_per_node),
    }
    for key in ("WANDB_API_KEY", "WANDB_PROJECT", "WANDB_NAME", "WANDB_ENTITY", "WANDB_MODE"):
        value = os.environ.get(key)
        if value:
            base_env[key] = value
    base_env.update(nccl_env)  # NCCL_SOCKET_IFNAME, NCCL_IB_DISABLE, etc.

    # ---- Per-node Ray task ----
    @ray.remote(num_gpus=args.gpus_per_node)
    def run_node_task(rank: int, env_overrides: Dict[str, str], megatron_args: List[str]) -> int:
        import os
        import subprocess
        import sys as _sys

        env = os.environ.copy()
        # Ray already set CUDA_VISIBLE_DEVICES based on num_gpus; respect it.
        env.update(env_overrides)
        env["NODE_RANK"] = str(rank)

        cmd = ["megatron", "sft"] + list(megatron_args)
        print(f"[node {rank}] CUDA_VISIBLE_DEVICES={env.get('CUDA_VISIBLE_DEVICES', '?')}", flush=True)
        print(f"[node {rank}] running: {' '.join(cmd)}", flush=True)
        try:
            proc = subprocess.run(cmd, env=env)
            return proc.returncode
        except KeyboardInterrupt:
            return 130
        except Exception as e:
            print(f"[node {rank}] ERROR: {e}", file=_sys.stderr, flush=True)
            return 1

    # Pin each task to a specific node so rank 0 lands on master
    futures = []
    for rank, node in enumerate(nodes):
        f = run_node_task.options(
            scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=node["NodeID"], soft=False),
            name=f"megatron-rank{rank}",
        ).remote(rank, base_env, megatron_args)
        futures.append((rank, f))

    print(f"[ray-launch] submitted {len(futures)} tasks; waiting for completion...\n")

    future_to_rank = {f: rank for rank, f in futures}
    rcs: Dict[int, int] = {}
    try:
        while future_to_rank:
            done, _ = ray.wait(list(future_to_rank), num_returns=1)
            for f in done:
                rank = future_to_rank.pop(f)
                try:
                    rc = ray.get(f)
                except Exception as e:
                    print(f"[ray-launch] node{rank} failed with Ray exception: {e}", file=sys.stderr)
                    for other in future_to_rank:
                        ray.cancel(other, force=True)
                    return 1
                rcs[rank] = rc
                print(f"[ray-launch] node{rank} exited with code {rc}")
                if rc != 0:
                    print(f"[ray-launch] node{rank} failed; cancelling remaining nodes...")
                    for other in future_to_rank:
                        ray.cancel(other, force=True)
                    return 1
    except KeyboardInterrupt:
        print("[ray-launch] interrupted, cancelling tasks...")
        for f in future_to_rank:
            try:
                ray.cancel(f, force=True)
            except Exception:
                pass
        return 130

    print()
    ordered_rcs = [rcs.get(rank, 1) for rank in range(nnodes)]
    if any(rc != 0 for rc in ordered_rcs):
        print(f"[ray-launch] FAILED (return codes: {ordered_rcs})")
        return 1
    print("[ray-launch] all nodes finished successfully")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
